/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Samples
         * @description The 25 solved cases, for the frontend to load as starting points.
         */
        get: operations["list_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sample
         * @description Rebuild a full analyze payload from the dataset, so the frontend can
         *     load a realistic case and then let the user edit it.
         */
        get: operations["get_sample_api_samples__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Request */
        post: operations["analyze_request_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Batch
         * @description Sequential rather than concurrent: the engine is pure CPU work with no
         *     I/O to overlap, so threads would add contention without throughput.
         */
        post: operations["analyze_batch_api_analyze_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accuracy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accuracy
         * @description Score the engine against the 25 solved samples.
         *
         *     Runs the real pipeline, not a cached result file: if the engine regresses,
         *     this endpoint shows it immediately.
         */
        get: operations["accuracy_api_accuracy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccuracyRow */
        AccuracyRow: {
            /** Request Id */
            request_id: string;
            /** User Id */
            user_id: string;
            /** Request Type */
            request_type: string;
            /** Currency */
            currency: string;
            /** Requested Amount */
            requested_amount: number;
            /** Expected Status */
            expected_status: string;
            /** Predicted Status */
            predicted_status: string;
            /** Status Match */
            status_match: boolean;
            /** Expected Method */
            expected_method: string;
            /** Predicted Method */
            predicted_method: string;
            /** Method Match */
            method_match: boolean;
            /** Expected Amount */
            expected_amount: number;
            /** Predicted Amount */
            predicted_amount: number;
            /** Relative Error */
            relative_error: number;
            /** Rejections */
            rejections: string[];
        };
        /** AccuracySummary */
        AccuracySummary: {
            /** Total */
            total: number;
            /** Status Correct */
            status_correct: number;
            /** Method Correct */
            method_correct: number;
            /** Amount Within 2Pct */
            amount_within_2pct: number;
            /** Amount Within 10Pct */
            amount_within_10pct: number;
            /** Median Relative Error */
            median_relative_error: number;
            /** Rows */
            rows: components["schemas"]["AccuracyRow"][];
        };
        /** AnalyzeRequest */
        "AnalyzeRequest-Input": {
            profile: components["schemas"]["ProfileIn-Input"];
            /** Events */
            events: components["schemas"]["EventIn-Input"][];
            /** Payment Options */
            payment_options?: components["schemas"]["PaymentOptionIn-Input"][];
            request: components["schemas"]["RequestIn-Input"];
            /**
             * Resolution
             * @default daily
             */
            resolution: string;
        };
        /** AnalyzeRequest */
        "AnalyzeRequest-Output": {
            profile: components["schemas"]["ProfileIn-Output"];
            /** Events */
            events: components["schemas"]["EventIn-Output"][];
            /** Payment Options */
            payment_options?: components["schemas"]["PaymentOptionIn-Output"][];
            request: components["schemas"]["RequestIn-Output"];
            /**
             * Resolution
             * @default daily
             */
            resolution: string;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            decision: components["schemas"]["DecisionOut"];
            projection: components["schemas"]["ProjectionOut"];
            reasoning: components["schemas"]["ReasoningOut"];
        };
        /** DecisionOut */
        DecisionOut: {
            /** Amount Safe To Pay */
            amount_safe_to_pay: number;
            /** Affordability Status */
            affordability_status: string;
            /** Recommended Payment Method */
            recommended_payment_method: string;
            /** Payment Plan */
            payment_plan: components["schemas"]["PaymentOut"][];
            /** Earliest Date For Full Payment */
            earliest_date_for_full_payment: string | null;
            /** Spending Changes Needed */
            spending_changes_needed: string[];
            /** Decision Explanation */
            decision_explanation: string;
        };
        /** EventIn */
        "EventIn-Input": {
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Direction */
            direction: string;
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Settlement Date */
            settlement_date?: string | null;
            /**
             * Status
             * @default settled
             */
            status: string;
            /**
             * Flexibility
             * @default fixed
             */
            flexibility: string;
            /** Minimum Allowed Amount */
            minimum_allowed_amount?: number | string | null;
            /**
             * Linked Event Id
             * @default
             */
            linked_event_id: string;
        };
        /** EventIn */
        "EventIn-Output": {
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Category
             * @default
             */
            category: string;
            /** Direction */
            direction: string;
            /** Amount */
            amount?: string | null;
            /** Currency */
            currency: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Settlement Date */
            settlement_date?: string | null;
            /**
             * Status
             * @default settled
             */
            status: string;
            /**
             * Flexibility
             * @default fixed
             */
            flexibility: string;
            /** Minimum Allowed Amount */
            minimum_allowed_amount?: string | null;
            /**
             * Linked Event Id
             * @default
             */
            linked_event_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaymentOptionIn */
        "PaymentOptionIn-Input": {
            /** Payment Option Id */
            payment_option_id: string;
            /** Payment Method */
            payment_method: string;
            /** Payment Amount */
            payment_amount: number | string;
            /**
             * Number Of Payments
             * @default 1
             */
            number_of_payments: number;
            /** First Payment Date */
            first_payment_date?: string | null;
            /** Payment Frequency Days */
            payment_frequency_days?: number | null;
            /**
             * Financing Fee
             * @default 0
             */
            financing_fee: number | string;
            /** Total Payable Amount */
            total_payable_amount?: number | string | null;
        };
        /** PaymentOptionIn */
        "PaymentOptionIn-Output": {
            /** Payment Option Id */
            payment_option_id: string;
            /** Payment Method */
            payment_method: string;
            /** Payment Amount */
            payment_amount: string;
            /**
             * Number Of Payments
             * @default 1
             */
            number_of_payments: number;
            /** First Payment Date */
            first_payment_date?: string | null;
            /** Payment Frequency Days */
            payment_frequency_days?: number | null;
            /**
             * Financing Fee
             * @default 0
             */
            financing_fee: string;
            /** Total Payable Amount */
            total_payable_amount?: string | null;
        };
        /** PaymentOut */
        PaymentOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
        };
        /** ProfileIn */
        "ProfileIn-Input": {
            /**
             * User Id
             * @default user
             */
            user_id: string;
            /** Home Currency */
            home_currency: string;
            /** Current Available Balance */
            current_available_balance: number | string;
            /** Minimum Balance To Keep */
            minimum_balance_to_keep: number | string;
            /** Financial Priorities */
            financial_priorities?: string[];
            /** Expense Categories To Protect */
            expense_categories_to_protect?: string[];
            /** Expense Categories User Is Willing To Reduce */
            expense_categories_user_is_willing_to_reduce?: string[];
            /** Expense Categories User Is Willing To Stop */
            expense_categories_user_is_willing_to_stop?: string[];
            /** Payment Methods User Will Consider */
            payment_methods_user_will_consider?: string[];
            /** Max Installment Months */
            max_installment_months?: number | null;
        };
        /** ProfileIn */
        "ProfileIn-Output": {
            /**
             * User Id
             * @default user
             */
            user_id: string;
            /** Home Currency */
            home_currency: string;
            /** Current Available Balance */
            current_available_balance: string;
            /** Minimum Balance To Keep */
            minimum_balance_to_keep: string;
            /** Financial Priorities */
            financial_priorities?: string[];
            /** Expense Categories To Protect */
            expense_categories_to_protect?: string[];
            /** Expense Categories User Is Willing To Reduce */
            expense_categories_user_is_willing_to_reduce?: string[];
            /** Expense Categories User Is Willing To Stop */
            expense_categories_user_is_willing_to_stop?: string[];
            /** Payment Methods User Will Consider */
            payment_methods_user_will_consider?: string[];
            /** Max Installment Months */
            max_installment_months?: number | null;
        };
        /** ProjectionOut */
        ProjectionOut: {
            /** Points */
            points: components["schemas"]["ProjectionPoint"][];
            /** Minimum Balance */
            minimum_balance: number;
            /**
             * Trough Date
             * Format: date
             */
            trough_date: string;
            /** Trough Balance */
            trough_balance: number;
            /** Headroom */
            headroom: number;
        };
        /** ProjectionPoint */
        ProjectionPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Balance */
            balance: number;
        };
        /** ReasoningOut */
        ReasoningOut: {
            /** Detected Series */
            detected_series: components["schemas"]["SeriesOut"][];
            /** Confirmed Future Events */
            confirmed_future_events: components["schemas"]["EventIn-Output"][];
            /** Rejected Plans */
            rejected_plans: string[];
            /** Income Projected */
            income_projected: boolean;
        };
        /** RequestIn */
        "RequestIn-Input": {
            /**
             * Request Id
             * @default request
             */
            request_id: string;
            /**
             * Request Date
             * Format: date
             */
            request_date: string;
            /**
             * Request Type
             * @default purchase
             */
            request_type: string;
            /** Requested Amount */
            requested_amount: number | string;
            /** Desired Completion Date */
            desired_completion_date?: string | null;
            /**
             * Allows Partial Payment
             * @default false
             */
            allows_partial_payment: boolean;
            /**
             * Request Text
             * @default
             */
            request_text: string;
        };
        /** RequestIn */
        "RequestIn-Output": {
            /**
             * Request Id
             * @default request
             */
            request_id: string;
            /**
             * Request Date
             * Format: date
             */
            request_date: string;
            /**
             * Request Type
             * @default purchase
             */
            request_type: string;
            /** Requested Amount */
            requested_amount: string;
            /** Desired Completion Date */
            desired_completion_date?: string | null;
            /**
             * Allows Partial Payment
             * @default false
             */
            allows_partial_payment: boolean;
            /**
             * Request Text
             * @default
             */
            request_text: string;
        };
        /** SeriesOut */
        SeriesOut: {
            /** Category */
            category: string;
            /** Direction */
            direction: string;
            /** Period Days */
            period_days: number;
            /** Amount */
            amount: number;
            /** Monthly Equivalent */
            monthly_equivalent: number;
            /**
             * Last Seen
             * Format: date
             */
            last_seen: string;
            /** Flexibility */
            flexibility: string;
            /** Occurrences */
            occurrences: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_samples_api_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_sample_api_samples__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeRequest-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_request_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_batch_api_analyze_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accuracy_api_accuracy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccuracySummary"];
                };
            };
        };
    };
}
